### PR TITLE
Change in docs for Laravel9

### PR DESCRIPTION
**Pull request by Flinty916**
Hey,

Checked this out, works great for interaction verification so far, just wanted to update the docs for any future devs wanting to use this, as the example wasn't quite correct for newer Laravel versions.

Thanks!

### CODE REVIEW

**Comment by nwilging** [comment]
Thanks for the contribution! Just wanted to note a couple things though:

First, the package documentation uses an example of [binding interfaces to implementations](https://laravel.com/docs/9.x/container#binding-interfaces-to-implementations). This is still part of the L9 docs, and is the way that I would prefer users to implement this package. Hinting an interface in a consuming class's constructor is a lot more powerful than directly injecting the concrete service.

Second, I believe that `private` vs `protected` is a decision left up to the developer implementing this package. I have no problem changing `protected` to `private` in the docs of this package, but I would still encourage users to use the interface type hint.

This PR can be accepted if it can be altered to something similar to:
```
...
    private DiscordInteractionServiceInterface $interactionService;
    
    public function __construct(DiscordInteractionServiceInterface $interactionService)
    {
        $this->interactionService = $interactionService;
    }
...
```

If there is other documentation specific to L9 that says otherwise, I am certainly open to looking at it.

Really glad the functionality is working out for you too!

**Comment by Flinty916** [comment]
When working in php8+ (think I'm on 8.1.6), my IDE couldn't find a declaration for the Interface, hence the change to the implementation. 

I don't disagree with you on it, just made the change for the sole purpose of it not working 👍

**Comment by nwilging** [comment]
> 

ah, the issue is that it's `DiscordInteractionServiceContract` and not `DiscordInteractionServiceInterface`.

This namespace should work:
```
use Nwilging\LaravelDiscordBot\Contracts\Services\DiscordInteractionServiceContract;
```

feel free to update the changes in this PR, or you can close it and I can update the readme in the very near future 😃 

thanks again for the contribution

**Review by nwilging — APPROVED** [review]

**Comment by Flinty916** [comment]
Not to worry, thanks for a great package, really saved me some work there!

**Pull request merged**
